#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    total = 0
    a = 1
    b = 1
    
    for i in range(n):
        c = a + b
        a = b 
        b = c
#        print(c)
        if c > n:
            break
        elif c % 2 == 0:
                total = c + total
        else:
            pass
            
    print(total)
        
        
    
